# Generated by Django 5.0.4 on 2024-04-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_is_employee_customuser_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(default='pending', max_length=15),
        ),
    ]
